In [4]:
import numpy as np
# input into perceptron
X = np.array([[2, 1],
              [1, -1],
              [-2, -1],
              [-1, 1]])
y = np.array([1, 1, -1, -1])
# code the perceptron such that it should output the weights

In [5]:
X.shape[0]

(4, 2)

In [8]:
ones_to_merge = np.ones((X.shape[0],1))

In [10]:
np.hstack([X,ones_to_merge])

array([[ 2.,  1.,  1.],
       [ 1., -1.,  1.],
       [-2., -1.,  1.],
       [-1.,  1.,  1.]])

In [ ]:
# 1. Add the 1s to X
# 2. Initialze random weights
# 3. Start with perceptron - visit every point
# 4. Calculate y predicted for every point
# 5. check for misclassification
# 6. Update weight if applicable
# 7. Repeat steps 3 to 6 for specifed number of epochs

In [12]:
def perceptron(X,y,lr, epochs):
  ones_to_merge = np.ones((X.shape[0],1))
  X = np.hstack([X,ones_to_merge])
  w = np.ones(X.shape[1])
  for j in range(epochs):
    for i in range(X.shape[0]):
      y_pred = np.dot(X[i],w)
      y_pred_sign = -1 if y_pred<0 else 1
      if y_pred_sign!=y[i]:
        w = w + X[i]*y[i]*lr


  return w


In [17]:
X = np.array([[2, 1],
              [1, -1],
              [-2, -1],
              [-1, 1]])
y = np.array([1, 1, -1, -1])
lr = 0.1
epochs = 10
perceptron(X,y,lr, epochs)

array([1.4, 0.6, 0.6])

In [18]:
ones_to_X = np.ones((X.shape[0],1))
w = perceptron(X,y,lr, epochs)
X = np.hstack([X, ones_to_X])
np.dot(X,w)

array([ 4. ,  1.4, -2.8, -0.2])

In [19]:
1, 1, -1, -1

(1, 1, -1, -1)